server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.30.1.65:3306/chatbotTest?serverTimezone=Asia/Seoul
#    username: chatbot
#    password: nara1234
    url: jdbc:mysql://172.31.42.210:3306/chatbotTest?serverTimezone=Asia/Seoul
    username: chatbot
    password: nara123
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  task:
    scheduling:
      pool:
        size: 8